remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

title: The Timbresmith's Shop
description: Building muscial instruments out of wood

collections_dir: collections
collections:
  projects:
    output: true
  techniques:
    output: true
